### PR TITLE
Update of translation files

### PR DESCRIPTION
**Pull request by glont**
Backgrounds File
----------------

- Append (SRD) to label
- Add translation for Acolyte

Classes File
------------

- Remove inline styling, this in turn fixed problem with babarian table having 
  over 200% in width
- Add compendium links for equipment of classes

Classfeatures File
------------------

- Fix Ids so that the translation can be applied
    - It seems that the new version of the dnd5e system v2.x did those changes
    - OLD ID -> NEW ID
    - Fighting Style: Two Weapon Fighting -> Fighting Style: Two-Weapon Fighting
    - Invocation: Life Drinker -> Invocation: Lifedrinker
    - Invocation: Otherwordly Leap -> Invocation: Otherworldly Leap
- Fix translation of Evocation Savant: 'Bannmagie' corrected to 'Hervorrufung'
- Add translation for Unarmed Strike (Monk)
- remove / replace br tags
- remove inline styles, but keep text-align
- remove invisible characters
- remove / replace non ascii spaces
- remove notes, which are not true anymore, example: Lay on Hands
- added secret sections for some other notes, where it seems to not be useful every time it is posted to chat

Items File
----------

- Fix Ids so that the translation can be applied
    - Most, if not all of those, where already broken in dnd5e system v1.6.x
    - OLD ID -> NEW ID
    - Alchemist's supplies -> Alchemist's Supplies
    - Arrows -> Arrow
    - Figurine of Wondrous Power Variant -> Figurine of Wondrous Power (Variant)
        - Where Variant is one of multiple values, for example Bronze Griffon
    - Gaming Set of Chess -> Chess Set
    - Gaming Set of Dice -> Dice Set
    - Gaming Set of Playing Cards -> Playing Cards Set
    - Navigator’s Tools -> Navigator's Tools
    - Poisoner’s Kit -> Poisoner's Kit
    - Spell Scroll Cantrip Level -> Spell Scroll Cantrip
    - Thieves’ Tools -> Thieves' Tools
- Clean up translations
    - replaced non ascii spaces / space look alike with ascii space
    - Carpet of Flying, removed inline style of table and added rolltable
- Add translations for
    - Bit and Bridle
    - Carpet of Flying Variants
    - Exotic Saddle
    - Feed
    - Marvelous Pigments
    - Military Saddle
    - Pack Saddle
    - Riding Saddle
    - Saddlebags
    - Truth Serum
- remove br tags
- remove inline styles, but keep text-align
- added secret sections for some notes, where it seems to not be useful every time it is posted to chat
    
Monsterfeatures File
-----------------------

- Add translation for most of the entries
- This is a first translation, so it may have some problems
- Bigger Issue: German is a gendered language. Most often I used the female
  form, mostly because it looked nicer: "Die {creature} kann". That means that
  when using those entries a user may need to change this manually. Someone
  better with writing may find a better solution for this.
  
Monsters File
---------------

- Add missing names and source from old javascript file.
- Add translations for actions, items and similar
    - NOTE: Because babelle is smart it tries to take this from other
      translations, so I tried to only include what is needed
    - For example most spells are not added, because it can use the
      spell translations directly, when the name is the same
    - Does not work sometimes, because a restriction is added in the name.
    - First translation, may have issues and missing content
- This file is the biggest change, it also increased in lines by almost 10x...

Races File
-----------

- autoformat
- removed inline styles
- added secret sections for notes

Subclasses File
----------------

- Append (SRD) to label
- Add names and sources
- No description yet

Spells File
-----------

- remove / replace br tags
- remove inline styles, but keep text-align
- remove invisible characters
- remove / replace non ascii spaces

Tables File
-----------

- Append (SRD) to label
- Otherwise I did nothing for this file

### CODE REVIEW

**Comment by glont** [comment]
@mhilbrunner

Ich hoffe es macht Sinn die Änderungen direkt via git zu pflegen anstatt über die Webseite.

**Comment by mhilbrunner** [comment]
@glont Thanks for the ping, I missed this. Awesome work! Need to discuss with the maintainer of the website how to merge this, will get back to you on that.

> ID fixes & It seems that the new version of the dnd5e system v2.x did those changes

Thanks, didn't have time to look into that yet, these could be huge.
Likewise if the inline styling changes fix the width issue when looking at some items on the sheet. That was a bother.

> Most often I used the female form, mostly because it looked nicer: "Die {creature} kann".

Personally, due do this I found `{creature}` kinda weird. In my personal stuff, I simply use "die Kreatur" without having the name inserted because it ends up reading less weird. Maybe we should switch to that for german? As a DM you usually know what creature you're using, and as a player it's a spoiler anyway.

> replaced non ascii spaces / space look alike with ascii space

Thanks, that was an annoyance on my todo list :)

> added secret sections for some other notes

Makes sense to me as well. Need to have a deeper look at the exact changes though. Also not sure how far we want to go in editorializing/making these decisions in a translations module that should IMO strive to stay fairly close to upstream. Need to have a look :)

> Monster Changes

Need to look at these in-depth too. The biggest current problem was that it blindly tried to match everything by name, which was a problem in cases where Spells collided with Monster Features, or Player Feature names collided with Monster Features.
Also there's stuff like "Multiattack" which usually is unique per monster but is only translated generically, which is wrong.

I'll have a look, discuss with the others and then we'll see. Thanks for contributing! :)

**Comment by glont** [comment]
> Personally, due do this I found {creature} kinda weird. In my personal stuff, I simply use "die Kreatur" without having the name inserted because it ends up reading less weird. Maybe we should switch to that for german? As a DM you usually know what creature you're using, and as a player it's a spoiler anyway.

That may make more sense. Sometimes "die Kreatur" is used for the Target of an ability, that should then be changed to "das Ziel".

> Need to look at these in-depth too. The biggest current problem was that it blindly tried to match everything by name, which was a problem in cases where Spells collided with Monster Features, or Player Feature names collided with Monster Features.
Also there's stuff like "Multiattack" which usually is unique per monster but is only translated generically, which is wrong.

My changes should help with that, even though they might not yet be "perfect", but it should at least in most cases remove the issue with things like Multiattack.

I also know that this is quite a large changeset, so I tried to describe what I did in the files.

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Alright, finally reviewed everything & talked to the others. Amazing work! Outstanding. :)

I think this is the biggest contribution we ever got, by far. Will take this chance to do a few larger scale changes to the JSON files as we need to merge it back with the website afterwards anyway, and then release a new version.

If you want to discuss anything further, feel free to ping me here or on Discord (you can find me on the official Foundry Discord under the same name: <https://discord.gg/foundryvtt>).

**Comment by mhilbrunner** [comment]
@glont Okay if I credit you in the README like the others? This was a sizeable contribution after all.
Would you want the name "glont" added, or something else?

**Comment by glont** [comment]
@mhilbrunner That would be nice and glont is fine.

**Pull request merged**
